### PR TITLE
Use semantic id for tracks and missions

### LINKED ISSUE #52: Semantic url
Bad:

https://missions.nitlanguage.org/missions/57bf3089d366b101c74f83dc

Good:

https://missions.nitlanguage.org/missions/pep8/simple_addition

### PR DESCRIPTION
**Pull request by privat**
eg. http://http://missions-dev.nitlanguage.org//missions/Pep8:Addition_simple (once deployed)

I do not know if (and how) have betters pages names.

close #52

### CODE REVIEW

**Comment by ppepos** [comment]
Could we actually use a _slugified_ mission name as identifier?

**Comment by privat** [comment]
It is what the PR does in fact, there is no _could_ (I had an hard time to understand what you asked in fact).

The `id` field is made required in the init of Mission and Track, and the `strip_id` method (a simple slugish method) is used to transform the title into an id.

**Comment by ppepos** [comment]
+1

**Comment by Morriar** [comment]
+1

**Pull request merged**
