### PR TITLE
docker support

### PR DESCRIPTION
**Pull request by privat**
# HOWTO
1. install docker. https://docs.docker.com/engine/installation/
2. install docker-compose. https://docs.docker.com/compose/install/
3. run `docker-compose up` in the root directory; (ctrl-C to close)
4. open http://localhost:3000
# DATA
- `db/` is the persistent mongo database.
  It is used (shared) by the mongo docker
- `out/` is the submission directory
  It is provided so the admin can manage/grep/whatever the directory
# TODO
- check good practices
- devel/prod versions
- reduce image size
- deploy and CI

### CODE REVIEW

**Comment by ppepos** [comment]
+1

**Comment by lbajolet** [comment]
+1

**Comment by Morriar** [comment]
The PR description should be in the README

**Comment by privat** [comment]
reroll: updated doc

**Comment by privat** [comment]
test this please

**Comment by privat** [comment]
test this please

**Pull request merged**
