### PR TITLE
Better errors

### PR DESCRIPTION
**Pull request by Morriar**
Fixes error handling:
- `/api/*` requests not matched by popcorn will return a `{ status: 404, message: "Not found" }` error
- `/*` requests not matched by angular will return a `404 Not found` html page

Also improved error messages returned by the API.

### CODE REVIEW

**Comment by Morriar** [comment]
SHould fix #28

**Comment by privat** [comment]
+1

**Comment by Morriar** [comment]
test this please

**Comment by privat** [comment]
test this please

**Comment by lbajolet** [comment]
+1

**Pull request merged**
