### PR TITLE
tests: more tests and use nitunit

### PR DESCRIPTION
**Pull request by Morriar**
* Create new tests for model entities
* Migrate existing tests to nitunit (except `curl_me` and `casperjs`)
* Migrate makefiles

### CODE REVIEW

**Comment by Morriar** [comment]
test this please

**Comment by Morriar** [comment]
I updated the Jenkins configuration to run `make check` instead of building `test_pep8`.

Let's see.

**Comment by Morriar** [comment]
test this please

**Review by privat — APPROVED** [review]
good job.

**Comment by privat** [comment]
I forgot to include the tests results in Jenkins: here they are http://gresil.org/jenkins/view/Missions/job/mission-CI/193/testReport/ (and numbers are visible in github)

**Pull request merged**
