### PR TITLE
Serve ressources from markdown descriptions

### LINKED ISSUE #64: Allow img in markdown descriptions
The main question is where to store the images, in the DB?
Do the mongo binding support large binary data?
How to serve them?
Can nitcorn now send binary without trying to clean-utf8 it?

Should we just assume the image are on disk? I do not like it because it adds another complexity but the code could be easier: I can copy the images in some data directory and make nitcorn serve them directly.

### PR DESCRIPTION
**Pull request by privat**
This extends to loader to accumulates resources in a data directory that will be served as is.

close #64

### CODE REVIEW

**Comment by lbajolet** [comment]
+1

**Comment by ppepos** [comment]
+1

**Comment by privat** [comment]
Angular seems to hijack the links to data/*
Is there anyway to exclude this route?

**Comment by ppepos** [comment]
If I'm understanding the [$location docs](https://docs.angularjs.org/guide/$location) correctly, hrefs with a `target` attribute will not be rewritten by angular. Is it what you're looking for?

**Pull request merged**
