### PR TITLE
More 404

### LINKED ISSUE #61: Error on invalid UI query
Maybe the generic 404 is enough.
- https://missions.nitlanguage.org/tracks/fail
- https://missions.nitlanguage.org/missions/fail
- https://missions.nitlanguage.org/players/fail

### LINKED ISSUE #89: bad page player if logged out
log out, then goes to

https://missions.nitlanguage.org/player/

a lot of mustaches

### PR DESCRIPTION
**Pull request by Morriar**
Closes #61 
Closes #89

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
If fact, I want to remove my +1
When I load (or reload) a legit page, I can see a transient "ressource not found" message

e.g. http://missions-dev.nitlanguage.org/tracks/Pep8

**Comment by Morriar** [comment]
Reroll

404 panels shown only when an error occurs.

**Comment by privat** [comment]
+1

**Pull request merged**
