### PR TITLE
Migrate to state views

### PR DESCRIPTION
**Pull request by ppepos**
Signed-off-by: Philippe Pepos Petitclerc ppeposp@gmail.com

### CODE REVIEW

**Comment by privat** [comment]
This seems functional. What are the changes?

**Review by privat — APPROVED** [review]

**Comment by privat** [comment]
bug in the breadcrumb:
- go to http://missions-dev.nitlanguage.org/track/Pep8/Pep8:Addition_simple
- click on 'Addition simple' in the navbar

**Comment by Morriar** [comment]
Breadcrumbs still use the old `/tracks` url. Maybe related to @privat problem

**Comment by Morriar** [comment]
The `login` link on the index page (when not logged) doesn't seem to work

**Comment by Morriar** [comment]
I'm talking about this one:

image

**Comment by ppepos** [comment]
Rerolled

**Pull request merged**
